"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Box, Braces, Cloud, Code2, ExternalLink, Mail, Menu, Radio, Rocket, Server, TestTube2, X } from "lucide-react";

const Github = Code2;
const Linkedin = Braces;

const nav = ["Home","About","Skills","Experience","Projects","DevOps","Contact"];
const skillGroups = {
  Frontend:["React","Next.js","JavaScript","TypeScript","Tailwind CSS","HTML","CSS"],
  Backend:["Node.js","Express","REST APIs","JWT","Sequelize"],
  Database:["MySQL","PostgreSQL"],
  "Cloud & DevOps":["AWS","Docker","GitHub Actions","CI/CD","Linux","Nginx","PM2"],
  "IoT & Communication":["MQTT","ESP32","Real-time communication"],
  Tools:["Git","GitHub","Postman","VS Code"],
};
const projects = [
  {name:"HRMS Application",desc:"Employee management, attendance, leave, permissions, reports and employee profiles in a real-world business application.",tech:["React Native","Node.js","Express","MySQL","JWT"],mark:"Real-world business application"},
  {name:"Ecommerce Platform",desc:"A full-stack platform with product management, shopping, shipping logic, admin features and customer enquiries.",tech:["Next.js","React","Node.js","Express","MySQL"],mark:"Full-stack application"},
  {name:"IoT / Smart Lock Platform",desc:"Smart lock devices connected to backend services through MQTT for live communication and device status updates.",tech:["Node.js","MQTT","ESP32","PostgreSQL","REST API"],mark:"IoT + real-time communication"},
  {name:"PurpleDrop Taxi",desc:"A responsive business website for a taxi service, focused on a clear and mobile-friendly customer experience.",tech:["React","JavaScript","HTML","CSS"],mark:"Responsive business experience"},
  {name:"Covai HomeTech",desc:"A responsive business web application designed for a home technology company.",tech:["React","JavaScript","Responsive UI"],mark:"Modern responsive UI"},
];
const reveal = { initial:{opacity:0,y:22}, whileInView:{opacity:1,y:0}, viewport:{once:true,margin:"-80px"}, transition:{duration:.6} };
function SectionHead({kicker,title,copy}:{kicker:string,title:string,copy?:string}) { return <motion.div {...reveal}><div className="eyebrow">{kicker}</div><h2 className="section-title">{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</motion.div> }

export function Portfolio(){
  const [scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false),[active,setActive]=useState("Home"),[more,setMore]=useState(false),[sent,setSent]=useState("");
  useEffect(()=>{const run=()=>{setScrolled(scrollY>20); const current=nav.map(n=>document.getElementById(n.toLowerCase())).filter(Boolean).reverse().find(s=>(s as HTMLElement).getBoundingClientRect().top<=90); if(current)setActive((current as HTMLElement).id[0].toUpperCase()+(current as HTMLElement).id.slice(1))}; run();addEventListener("scroll",run,{passive:true});return()=>removeEventListener("scroll",run)},[]);
  const scrollToSection=(event:React.MouseEvent<HTMLAnchorElement>,sectionId:string)=>{
    event.preventDefault();
    const target=document.getElementById(sectionId);
    if(!target)return;
    const navHeight=76;
    const sectionTop=target.getBoundingClientRect().top+window.scrollY;
    window.scrollTo({
      top:Math.max(0,sectionTop-navHeight),
      behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",
    });
    window.history.replaceState(null,"",`#${sectionId}`);
    setOpen(false);
  };
  const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const subject=encodeURIComponent(`Portfolio enquiry from ${f.get("name")}`); const body=encodeURIComponent(`${f.get("message")}\n\nFrom: ${f.get("name")} (${f.get("email")})`); setSent("Opening your email app…"); location.href=`mailto:lakshmanan@example.com?subject=${subject}&body=${body}`};
  return <>
    <header className={`nav ${scrolled?"scrolled":""}`}><div className="wrap navin"><a href="#home" className="logo" aria-label="Home" onClick={event=>scrollToSection(event,"home")}>&lt;L /&gt;</a><nav className={`links ${open?"open":""}`} aria-label="Main navigation">{nav.map(n=>{const id=n.toLowerCase();return <a key={n} href={`#${id}`} className={active===n?"active":""} onClick={event=>scrollToSection(event,id)}>{n}</a>})}</nav><button className="menu" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
    <main>
      <section id="home" className="hero"><div className="wrap hero-grid"><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="status"><i/>Available for meaningful opportunities</div><h1>Hi, I&apos;m <span>Lakshmanan.</span></h1><div className="hero-sub">Full Stack Developer — Building • Deploying • Improving</div><p className="hero-copy">I build real-world web and IoT applications using React, Next.js, Node.js and PostgreSQL, while exploring AWS, Docker and DevOps to understand the complete journey from development to production.</p><div className="actions"><a className="btn primary" href="#projects">View my work <ArrowRight size={16}/></a><a className="btn" href="#contact">Let&apos;s connect</a></div><div className="socials"><a className="iconbtn" href="https://github.com/iam-lakshmanan" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={18}/></a><a className="iconbtn" href="#contact" aria-label="LinkedIn"><Linkedin size={18}/></a><a className="iconbtn" href="#contact" aria-label="Email"><Mail size={18}/></a></div></motion.div><motion.div className="terminal card" initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{delay:.25,duration:.7}}><div className="term-top"><i/><i/><i/></div><div className="flow">{["Code","Backend","Database","Docker","AWS","Production"].map((x,i)=><div key={x}><div className="flow-row"><span>0{i+1}</span>{x}</div>{i<5&&<div className="flow-line"/>}</div>)}</div></motion.div></div></section>
      <section id="about" className="section"><div className="wrap"><SectionHead kicker="About" title="A little about me" copy="I’m a Full Stack Developer who enjoys building real-world applications and solving problems across frontend, backend, and deployment. I work mainly with React, Next.js, Node.js, Express, MySQL and PostgreSQL, and I’ve used MQTT to connect live IoT device data with applications. Now I’m going deeper into AWS, Docker, CI/CD and Linux to understand how software is deployed, monitored and maintained in production."/><div className="three">{[[Code2,"Build","Creating responsive and scalable applications."],[Radio,"Connect","Building APIs and real-time IoT communication."],[Rocket,"Deploy","Learning and implementing cloud and DevOps workflows."]].map(([Icon,t,d],i)=><motion.article className="card mini" key={String(t)} {...reveal} transition={{delay:i*.08}}><Icon size={23}/><h3>{t as string}</h3><p>{d as string}</p></motion.article>)}</div></div></section>
      <section id="skills" className="section"><div className="wrap"><SectionHead kicker="Toolkit" title="Technologies I work with" copy="A practical toolkit shaped by building across the browser, server, database, devices and deployment."/><div className="skills">{Object.entries(skillGroups).map(([group,items],i)=><motion.article className="card skill" key={group} {...reveal} transition={{delay:(i%3)*.06}}><h3>{group}</h3><div className="tags">{items.map(x=><span className="tag" key={x}>{x}</span>)}</div></motion.article>)}</div></div></section>
      <section id="experience" className="section"><div className="wrap"><SectionHead kicker="Experience" title="Building software that gets used"/><motion.article className="card experience" {...reveal}><div className="role-head"><div><h3>Full Stack Developer</h3><div className="company">Magnic Technologies</div></div><span className="tag">Web • IoT • Deployment</span></div><p className="section-copy">Building and maintaining full-stack web and IoT applications across frontend, backend, databases and deployment.</p><ul className="responsibilities">{["Develop applications with React, Next.js and Node.js","Build REST APIs and backend services","Work with PostgreSQL and MySQL","Create real-time IoT features using MQTT","Connect device data to web dashboards","Implement authentication and application security","Deploy applications using Docker and CI/CD","Troubleshoot production issues and improve reliability"].map(x=><li key={x}>{x}</li>)}</ul><div className="tags">{["React","Next.js","Node.js","PostgreSQL","MySQL","MQTT","Docker","Linux","Nginx","PM2"].map(x=><span className="tag" key={x}>{x}</span>)}</div></motion.article></div></section>
      <section id="projects" className="section"><div className="wrap"><SectionHead kicker="Selected work" title="Things I’ve built" copy="Real products, business workflows and connected systems—built to solve practical problems."/><div className="projects">{projects.slice(0,more?5:3).map((p,i)=><motion.article className="card project" key={p.name} {...reveal}><div className="project-visual"><span className="project-num">PROJECT / 0{i+1} — {p.mark}</span></div><div className="project-body"><h3>{p.name}</h3><p>{p.desc}</p><div className="tags">{p.tech.map(x=><span className="tag" key={x}>{x}</span>)}</div><div className="project-links"><a href="https://github.com/iam-lakshmanan" target="_blank" rel="noreferrer"><Github size={15}/> GitHub</a><a href="#contact">Discuss project <ExternalLink size={14}/></a></div></div></motion.article>)}</div><button className="btn" style={{marginTop:24}} onClick={()=>setMore(!more)}>{more?"Show fewer projects":"View more projects"} <ArrowRight size={15}/></button></div></section>
      <section id="devops" className="section"><div className="wrap"><SectionHead kicker="Cloud & DevOps" title="From code to production" copy="I’m expanding my Full Stack skills into Cloud and DevOps so I can understand the complete application lifecycle—from writing code to deploying and maintaining it in production."/><div className="pipeline">{["GitHub","GitHub Actions","Build & Test","Docker","AWS","Nginx","Production"].map((x,i)=><div style={{display:"contents"}} key={x}><motion.div className="card pipe-node" initial={{opacity:.45}} whileInView={{opacity:1,borderColor:"#397e6c"}} viewport={{once:true}} transition={{delay:i*.14}}>{x}</motion.div>{i<6&&<div className="pipe-arrow">→</div>}</div>)}</div><div className="devcards">{[[Cloud,"AWS","EC2 • S3 • RDS • IAM"],[Box,"Docker","Containers • Images • Deployment"],[TestTube2,"CI/CD","GitHub Actions • Automated deployment"],[Server,"Server","Linux • Nginx • PM2"]].map(([Icon,t,d])=><article className="card devcard" key={String(t)}><Icon size={21} color="#72e0bd"/><h3>{t as string}</h3><p>{d as string}</p></article>)}</div></div></section>
      <section className="section"><div className="wrap"><SectionHead kicker="Process" title="How I approach development"/><div className="steps">{[["01","Understand","Understand the requirement and problem before writing code."],["02","Build","Create clean, reusable frontend and backend components."],["03","Test & Debug","Find the root cause and improve reliability."],["04","Deploy & Improve","Ship, observe real usage and keep improving."]].map(([n,t,d])=><div className="step" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
      <section className="section"><div className="wrap"><SectionHead kicker="Currently exploring" title="Always learning. Always improving." copy="Experimenting, breaking things and figuring out how to make them better."/><div className="learning">{["AWS Cloud","Docker","CI/CD","Linux","System Design","Scalable Backends","Application Security"].map(x=><div className="card learn" key={x}><Braces size={17} color="#72e0bd"/>{x}</div>)}</div></div></section>
      <section className="section"><div className="wrap"><motion.div className="card github-box" {...reveal}><div><div className="eyebrow">Open source</div><h2>Code, experiments & projects</h2><p className="section-copy">Most of my learning happens by building. See the projects, experiments and ideas I’m currently working on.</p></div><a className="btn primary" href="https://github.com/iam-lakshmanan" target="_blank" rel="noreferrer"><Github size={17}/> Visit GitHub</a></motion.div></div></section>
      <section id="contact" className="section"><div className="wrap"><SectionHead kicker="Contact" title="Let’s build something" copy="Have a project, opportunity, or just want to talk about development and technology? I’d be happy to connect."/><div className="contact-grid"><div><p className="section-copy">The best conversations usually start with a simple hello.</p><div className="contact-list"><a className="contact-link" href="mailto:lakshmanan@example.com"><Mail size={18}/> Email</a><a className="contact-link" href="#"><Linkedin size={18}/> LinkedIn</a><a className="contact-link" href="https://github.com/iam-lakshmanan" target="_blank" rel="noreferrer"><Github size={18}/> github.com/iam-lakshmanan</a></div></div><form className="card form" onSubmit={submit}><div className="field"><label htmlFor="name">NAME</label><input id="name" name="name" required minLength={2} autoComplete="name"/></div><div className="field"><label htmlFor="email">EMAIL</label><input id="email" name="email" type="email" required autoComplete="email"/></div><div className="field"><label htmlFor="message">MESSAGE</label><textarea id="message" name="message" required minLength={10}/></div><button className="btn primary" type="submit">Send message <ArrowRight size={16}/></button><div className="form-status" aria-live="polite">{sent}</div></form></div></div></section>
    </main>
    <footer className="footer"><div className="wrap footer-in"><span>© 2026 Lakshmanan. Built with Next.js & Tailwind CSS.</span><span>Built with curiosity and lots of debugging.</span></div></footer>
  </>;
}
